import { Product } from './types';

export const CATEGORIES = [
  { id: 'all', title: 'All' },
  { id: 'abstract', title: 'Abstract' },
  { id: 'modern', title: 'Modern' },
  { id: 'nature', title: 'Nature' },
  { id: 'islamic', title: 'Islamic Art' },
  { id: 'minimalist', title: 'Minimalist' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Verona Luxe Canvas',
    category: 'abstract',
    type: 'Textured Canvas',
    pricePKR: 28500,
    rating: 4.8,
    image: '/uploads/watermarked-image11.jpg',
  },
  {
    id: 'p2',
    name: 'Nova Line Framed Art',
    category: 'modern',
    type: 'Framed Canvas',
    pricePKR: 32000,
    rating: 4.9,
    image: '/uploads/watermarked-image_22.jpg',
  },
  {
    id: 'p3',
    name: 'Vero Modular Masterpiece',
    category: 'abstract',
    type: 'Canvas Painting',
    pricePKR: 29500,
    rating: 4.7,
    image: '/uploads/watermarked-image_33.jpg',
  },
  {
    id: 'p4',
    name: 'Divine Calligraphy',
    category: 'islamic',
    type: 'Gold Leaf Canvas',
    pricePKR: 36000,
    rating: 4.9,
    image: '/uploads/watermarked-image_44.jpg',
  },
  {
    id: 'p5',
    name: 'Celestial Modern',
    category: 'modern',
    type: 'Acrylic Glass Art',
    pricePKR: 42000,
    rating: 4.6,
    image: '/uploads/watermarked-image_55.jpg',
  },
  {
    id: 'p6',
    name: 'Aura of Minimal',
    category: 'minimalist',
    type: 'Textured Wall Art',
    pricePKR: 38000,
    rating: 4.8,
    image: '/uploads/watermarked-image11.jpg',
  },
  {
    id: 'p7',
    name: 'Golden Forest Horizon',
    category: 'nature',
    type: 'Oil Paint Canvas',
    pricePKR: 34500,
    rating: 4.9,
    image: '/uploads/watermarked-image_22.jpg',
  },
  {
    id: 'p8',
    name: 'Sublime Calligraphy',
    category: 'islamic',
    type: 'Wood Framed Canvas',
    pricePKR: 39000,
    rating: 5.0,
    image: '/uploads/watermarked-image_33.jpg',
  },
  {
    id: 'p9',
    name: 'Ethereal Harmony',
    category: 'abstract',
    type: 'Mixed Media Art',
    pricePKR: 31000,
    rating: 4.7,
    image: '/uploads/watermarked-image_44.jpg',
  },
  {
    id: 'p10',
    name: 'Nordic Horizon Minimal',
    category: 'minimalist',
    type: 'Textured Linen',
    pricePKR: 27000,
    rating: 4.8,
    image: '/uploads/watermarked-image_55.jpg',
  },
  {
    id: 'p11',
    name: 'Midnight Bloom',
    category: 'nature',
    type: 'Botanical Canvas',
    pricePKR: 33000,
    rating: 4.9,
    image: '/uploads/watermarked-image11.jpg',
  },
  {
    id: 'p12',
    name: 'Geometric Monolith',
    category: 'modern',
    type: 'Architectural Print',
    pricePKR: 41000,
    rating: 4.8,
    image: '/uploads/watermarked-image_22.jpg',
  },
];

export const COLLECTION_IMAGES = [
  { id: 'c1', title: 'Serene Aura Canvas', desc: 'Museum-grade textured canvas featuring golden leaf brushstrokes.', src: '/collection/img1.jpg' },
  { id: 'c2', title: 'Contemporary Luxe', desc: 'Modern geometric composition crafted for luxury interior walls.', src: '/collection/img2.jpg' },
  { id: 'c3', title: 'Minimalist Form', desc: 'Clean architectural texture on premium museum cotton linen.', src: '/collection/img3.jpg' },
  { id: 'c4', title: 'Golden Horizon', desc: 'Serene organic landscape in warm honey & metallic gold tones.', src: '/collection/img4.jpg' },
  { id: 'c5', title: 'Modern Gallery', desc: 'Bold statement piece designed to elevate dining & hallway spaces.', src: '/collection/img5.jpg' },
  { id: 'c6', title: 'Abstract Masterpiece', desc: 'High-contrast textured oil art with deep charcoal palette.', src: '/collection/img6.jpg' },
  { id: 'c7', title: 'Ethereal Composition', desc: 'Soft neutral tones and fluid forms designed for calm rooms.', src: '/collection/img7.jpg' },
  { id: 'c8', title: 'Urban Elegance', desc: 'Modernist line artwork framed in solid handcrafted dark wood.', src: '/collection/img8.jpg' },
  { id: 'c9', title: 'Timeless Canvas', desc: 'Classic museum reproduction with protective matte varnish.', src: '/collection/img9.jpg' },
  { id: 'c10', title: 'Architectural Vista', desc: 'Geometric shadow art capturing depth, light & proportion.', src: '/collection/img10.jpg' },
];

export const HERO_SLIDES = [
  {
    image: '/slider/main1.png',
    badge: 'EXCLUSIVE CANVAS & FRAMED ART',
    titleLine1: 'Discover',
    pillText: 'Timeless',
    titleLine2: 'Art for Every Space',
    subtitle: 'Transform your home with stylish, durable, and comfortable wall art designed to elevate your living experience.',
    cta: 'Shop Now',
    linkText: 'Explore Collections',
    targetCategory: 'all',
  },
  {
    image: '/slider/main 2.png',
    badge: 'CURATED ABSTRACT COLLECTION',
    titleLine1: 'Explore',
    pillText: 'Abstract',
    titleLine2: 'Masterpieces & Textures',
    subtitle: 'Elevate modern interiors with bold brushstrokes, golden leaf accents, and expressive abstract forms.',
    cta: 'View Abstract',
    linkText: 'Explore Gallery',
    targetCategory: 'abstract',
  },
  {
    image: '/slider/main 3.png',
    badge: 'MODERN & GEOMETRIC HARMONY',
    titleLine1: 'Redefine',
    pillText: 'Modern',
    titleLine2: 'Luxury Living Decor',
    subtitle: 'Minimalist geometric compositions and contemporary aesthetic framed prints for sophisticated rooms.',
    cta: 'Shop Modern',
    linkText: 'See Details',
    targetCategory: 'modern',
  },
  {
    image: '/slider/main 4.png',
    badge: 'NATURE & LANDSCAPE CANVAS',
    titleLine1: 'Bring',
    pillText: 'Nature',
    titleLine2: 'Into Your Home',
    subtitle: 'Serene golden forests, mountain vistas, and calming organic landscape artwork crafted for tranquil spaces.',
    cta: 'Explore Nature',
    linkText: 'View Paintings',
    targetCategory: 'nature',
  },
  {
    image: '/slider/main 5.png',
    badge: 'HERITAGE & ISLAMIC CALLIGRAPHY',
    titleLine1: 'Celebrate',
    pillText: 'Islamic',
    titleLine2: 'Calligraphy & Heritage',
    subtitle: 'Intricate gold leaf calligraphy and sacred architectural artwork presented on museum-grade framed canvas.',
    cta: 'Shop Islamic Art',
    linkText: 'Explore Heritage',
    targetCategory: 'islamic',
  },
];

export const INSTA_POSTS = [
  {
    id: 1,
    src: '/slider/main1.png',
    handle: '@luxe_interiors_pk',
    likes: '1.8k',
    caption: 'Living room transformation with Galleria canvas',
    tilt: '-rotate-3',
  },
  {
    id: 2,
    src: '/collection/img1.jpg',
    handle: '@art_collector_lahore',
    likes: '2.4k',
    caption: 'Archival fluid art framed in solid wood',
    tilt: 'rotate-2',
  },
  {
    id: 3,
    src: '/slider/main 2.png',
    handle: '@modern.home.art',
    likes: '3.1k',
    caption: 'Gallery wall arrangement in master suite',
    tilt: '-rotate-2',
  },
  {
    id: 4,
    src: '/collection/img3.jpg',
    handle: '@interior_stylist_isb',
    likes: '1.5k',
    caption: 'Classical botanical masterpiece canvas',
    tilt: 'rotate-3',
  },
  {
    id: 5,
    src: '/slider/main 3.png',
    handle: '@galleria_living',
    likes: '4.2k',
    caption: 'Exhibition showcase at Galleria Studio',
    tilt: '-rotate-3',
  },
  {
    id: 6,
    src: '/collection/img5.jpg',
    handle: '@design_space_khi',
    likes: '2.9k',
    caption: 'Custom textured oil artwork installation',
    tilt: 'rotate-2',
  },
];
